export type RepoQATaskType = 'repoqa.index' | 'repoqa.query';

/** v0.6.0 — staged indexing pipeline phases broadcast over SSE/WebSocket. */
export type IndexingPhase =
  | 'DISCOVERY'
  | 'AST_EXTRACTION'
  | 'CROSS_LANG_BRIDGE'
  | 'FINALIZING';

export interface IndexingProgressPayload {
  repoId: string;
  phase: IndexingPhase;
  phaseLabel: string;
  currentFile?: string;
  processedFiles: number;
  totalFiles: number;
  /** 0..100 — 100 only on FINALIZING completion. */
  percent: number;
}

/** v0.6.0 — Architecture Delta symbol/edge summary used by CLI/API/UI. */
export interface ExtractedSymbol {
  name: string;
  file: string;
  lineStart: number;
  lineEnd: number;
  kind: string;
  parentType?: string;
  displayPath?: string;
}

export interface CallEdge {
  from: { file: string; method: string; line: number };
  to: { file: string; method: string; line: number };
}

export interface ArchitectureDeltaReport {
  schemaVersion: number;
  base: string;
  head: string;
  baseSha?: string;
  headSha?: string;
  addedRoutes: ExtractedSymbol[];
  removedRoutes: ExtractedSymbol[];
  brokenEdges: CallEdge[];
  impactedApis: Array<{
    routeSymbol: ExtractedSymbol;
    affectedBySymbols: string[];
    riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  }>;
  /** Reverse/delta Mermaid diagram; optional for small deltas. */
  mermaid?: string;
}

export interface IndexJobInput {
  repoUrl?: string;
  localPath: string;
  branch?: string;
  languages?: string[];
}

export interface IndexJobOutput {
  status: 'cloning' | 'parsing' | 'ready' | 'error';
  repoId: string;
  fileCount: number;
  symbolCount: number;
  error?: string;
}

export interface QueryJobInput {
  repoId: string;
  question: string;
  mode?: 'architecture' | 'call-chain' | 'environment';
}

export interface QueryJobOutput {
  answer: string;
  suggestedAction?: string;
  mermaid?: string;
  anchors?: Array<{
    file: string;
    line: number;
    symbol: string;
  }>;
  trace?: Array<{
    file: string;
    method: string;
    line: number;
  }>;
}

/* ------------------------------------------------------------------ */
/* v0.8.0 — Composite agent tools (deterministic engines)              */
/* ------------------------------------------------------------------ */

/**
 * Chain layers emitted by the diagnose engine. The four canonical layers cover
 * a Java full-stack trace (browser component → HTTP route → service → MyBatis
 * mapper/XML SQL). The model degrades gracefully per language: a TS repo has
 * no DATA_MAPPER layer and simply omits it — layers are never invented, so
 * `DiagnoseLayer` stays open for engine-emitted variants.
 */
export type DiagnoseLayer =
  | 'FRONTEND_COMPONENT'
  | 'HTTP_ROUTER'
  | 'SERVICE'
  | 'DATA_MAPPER'
  | (string & {});

export interface DiagnoseParams {
  repoId: string;
  /** Start symbol: a method name ("handleLike") or "METHOD /route/path". */
  entrySymbol: string;
  /** Free-text symptom, carried through to reports (never used for guessing). */
  symptomDescription?: string;
}

export interface DiagnoseChainStep {
  layer: DiagnoseLayer;
  symbol: string;
  filePath: string;
  line: number;
  status: 'VERIFIED' | 'BROKEN' | 'SUSPECT';
  /** Present on BROKEN steps: the deterministic static-analysis break reason. */
  diagnosticNotes?: string;
  codeSnippet?: string;
}

export interface DiagnoseResult {
  schemaVersion: number;
  repoId: string;
  /** Stable id derived from repo+entry; re-running the same query reuses it. */
  traceId: string;
  entrySymbol: string;
  verifiedChain: DiagnoseChainStep[];
  rootCauseSummary: string;
  /**
   * Empty on the deterministic tool by design (truth-source boundary): patches
   * are generated by the LLM orchestration layer and marked accordingly.
   */
  suggestedPatch?: string;
  suggestedPatchSource?: 'llm-generated';
  cockpitDeepLink: string;
}

export interface RefactorPlanParams {
  repoId: string;
  targetSymbol: string;
  changeType: 'SIGNATURE_CHANGE' | 'REMOVAL' | 'LOGIC_REFACTOR';
}

export interface RefactorPlanResult {
  schemaVersion: number;
  repoId: string;
  targetSymbol: string;
  target: { name: string; file: string; line: number };
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  directCallersCount: number;
  indirectCallersCount: number;
  /** Distinct route paths reachable upstream from the target. */
  impactedRoutes: string[];
  /** Frontend components bridged to the impacted routes (fetch/axios). */
  impactedFrontendComponents: string[];
  migrationSteps: string[];
  cockpitDeepLink: string;
}

/* ------------------------------------------------------------------ */
/* v0.9.0 — Module evolution & domain radar (deterministic engines)    */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/* Issue 24 / ADR-0014 — convention scanning contract (moved here from  */
/* the control-plane engine so evolution results can embed profiles     */
/* without the contracts package depending on it).                      */
/* ------------------------------------------------------------------ */

export type ConventionAxisId =
  | 'return_wrapping'
  | 'interface_impl_style'
  | 'base_class'
  | 'di_style'
  | 'package_layout';

export interface ConventionAnchor {
  file: string;
  line: number;
  symbol: string;
}

export interface ConventionCoverage {
  match: number;
  total: number;
}

export interface ConventionAxis {
  axis: ConventionAxisId;
  /** Language coverage gate: sniffing needs the parser facts it keys on. */
  supported: boolean;
  /** One-line factual claim, e.g. "Controllers return ApiResult<T> uniformly". */
  verdict?: string;
  /**
   * Machine-readable mirror of the verdict so consumers can branch on the
   * convention without parsing the sentence (Issue 24.3 placement). Present
   * only on decided, supported axes:
   * - return_wrapping: dominant wrapper class name (`ApiResult`) or `bare`;
   * - interface_impl_style: `split` | `plain`;
   * - di_style: `constructor` | `field`;
   * - base_class / package_layout: `base`|`none` / the dominant feature package.
   */
  primary?: string;
  coverage?: ConventionCoverage;
  anchors?: ConventionAnchor[];
  /** Minority side: always disclosed, never silently dropped (ADR-0014). */
  dissidents?: ConventionAnchor[];
  /**
   * Present only when a decided neighborhood overrides a conflicting global
   * majority (neighbor-first arbitration): the overridden global claim, kept
   * machine-readable so the split stays auditable (ADR-0014 disclosure).
   */
  globalVerdict?: { verdict: string; coverage: ConventionCoverage };
}

export interface ConventionProfile {
  repoId: string;
  /** Neighboring package used for the arbitration, when a target was given. */
  neighborPackage?: string;
  axes: ConventionAxis[];
  /** Physical commit of the sniffed tree (`hash` or `hash+dirty`). */
  sampledAt: string;
}

export interface ModuleEvolutionParams {
  repoId: string;
  /** `DEPRECATE` plans a safe teardown; `EXTEND` plans a decoupled attach. */
  intentType: 'DEPRECATE' | 'EXTEND';
  /** Module name / directory, or a main-flow symbol for EXTEND. */
  targetSymbolOrModule: string;
  /** Free-text extension goal, e.g. "异步敏感词审查"; never used for guessing. */
  extensionGoal?: string;
  /**
   * Issue 24.3 — explicit neighborhood override for the convention sniff
   * (dotted package names, e.g. the destination packages of a planned move).
   */
  nearPackages?: string[];
  /** Physical commit of the sniffed tree (`hash` or `hash+dirty`). */
  commit?: string;
}

export interface EvolutionChecklistItem {
  category: 'FRONTEND' | 'CONTROLLER' | 'SERVICE' | 'PERSISTENCE' | 'CONFIG';
  action: 'DELETE' | 'MODIFY' | 'CREATE';
  filePath: string;
  description: string;
}

export interface EvolutionScaffoldTemplate {
  suggestedPattern: 'SPRING_EVENT_ASYNC' | 'AOP_ASPECT' | 'DIRECT_INJECTION';
  filePath: string;
  codeSnippet: string;
}

export interface ModuleEvolutionResult {
  schemaVersion: number;
  repoId: string;
  intentType: 'DEPRECATE' | 'EXTEND';
  target: string;
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  blastRadius: {
    impactedCallersCount: number;
    impactedRoutes: string[];
    impactedComponents: string[];
    /** Public symbols that die with the module (fixed-point transitive scan). */
    orphanedSymbols: Array<{ name: string; filePath: string; line: number }>;
  };
  checklists: EvolutionChecklistItem[];
  /**
   * Deterministic scaffolds for EXTEND (recommended shapes, not patches).
   * Empty on DEPRECATE.
   */
  scaffoldTemplates?: EvolutionScaffoldTemplate[];
  /**
   * Empty on the deterministic engine by design (ADR-0006): patches belong to
   * the LLM orchestration layer and are marked llm-generated there.
   */
  suggestedPatch?: string;
  suggestedPatchSource?: 'llm-generated';
  /** Transaction boundary evidence (declaration-level only). */
  transactionBoundaries: Array<{
    symbol: string;
    filePath: string;
    line: number;
    /** METHOD / CLASS / INTERFACE declaration site of the annotation. */
    scope: 'METHOD' | 'CLASS' | 'INTERFACE';
  }>;
  /**
   * Issue 24.3 (ADR-0014) — the convention profile the EXTEND plan obeys,
   * neighbor-first arbitrated. Absent on DEPRECATE (dead code is structural).
   */
  conventions?: ConventionProfile;
  /**
   * Issue 24.3 — convention-driven placement for the DIRECT_INJECTION shape:
   * where the new files go, how the dependency wires in and what the handler
   * signature looks like. Absent on DEPRECATE and on event/aspect patterns
   * (their scaffolds are framework-fixed, not convention-governed).
   */
  placement?: EvolutionPlacement;
  /**
   * Issue 24.3 — soft findings (tolerance disclosure, ADR-0014): weakly
   * covered conventions the plan follows anyway, and transaction-decoupling
   * warnings. Risks never block; only STRICT intent conflicts do.
   */
  risks?: EvolutionRisk[];
  cockpitDeepLink: string;
}

/** One landing file of a convention-driven placement plan. */
export interface EvolutionPlacementFile {
  filePath: string;
  role: 'interface' | 'impl' | 'single';
}

export interface EvolutionPlacement {
  /** Destination package (dotted), derived from the attach point's real directory. */
  packagePath: string;
  files: EvolutionPlacementFile[];
  /** Dependency wiring prescribed by the di_style convention. */
  injection: {
    style: 'constructor' | 'field' | 'unsupported';
    codeSnippet: string;
  };
  /** Handler method signature shaped by the return_wrapping convention. */
  handlerSignature?: string;
  /** Convention axes the plan obeys — verdict-level traceability (ADR-0014). */
  basedOn: Array<{ axis: ConventionAxisId; verdict: string }>;
}

/** A non-blocking finding on the evolution plan (ADR-0014 tolerance). */
export interface EvolutionRisk {
  kind: 'transaction-warning' | 'convention-split';
  message: string;
  /** Human-executable decoupling advice (e.g. publish after commit). */
  suggestion?: string;
  axis?: ConventionAxisId;
  /** Minority-side anchors disclosed verbatim (ADR-0014). */
  divergentSamples?: ConventionAnchor[];
}

/**
 * Issue 24.3 — structured detail behind a ConventionConflictError: a user
 * intent colliding head-on with a STRICT convention axis (coverage ≥ 85%),
 * or an injection point that sits on an existing bean dependency cycle.
 */
export interface ConventionConflictDetail {
  /** Blocked axis; `injection-cycle` when a bean cycle blocks the injection point. */
  axis: ConventionAxisId | 'injection-cycle';
  verdict: string;
  coverage?: ConventionCoverage;
  anchors: ConventionAnchor[];
  /** Compliant rewrite suggestion — how to pass the strict gate. */
  suggestion: string;
}

export interface DomainRadarParams {
  repoId: string;
  /** Optional natural-language intent, e.g. "用户点赞". */
  query?: string;
}

export interface DomainRadarAnchor {
  symbol: string;
  type: 'CONTROLLER' | 'SERVICE' | 'ENTITY';
  /** 0..100 deterministic score: fuzzyMatchScore blended with graph rank. */
  relevanceScore: number;
  filePath: string;
  line: number;
  /** v0.11 — incoming call count from the static symbol graph. */
  inDegree: number;
  /** v0.11 — outgoing call count from the static symbol graph. */
  outDegree: number;
}

export interface DomainRadarHub {
  symbol: string;
  inDegree: number;
  outDegree: number;
  /** Deterministic pagerank 0..1 (damping 0.85, sink mass redistributed). */
  pagerank: number;
  role: string;
}

export interface DomainRadarResult {
  schemaVersion: number;
  repoId: string;
  matchedAnchors: DomainRadarAnchor[];
  hubNodes: DomainRadarHub[];
  /** Route entries sorted by graph rank, e.g. "GET /api/owners — listOwners". */
  topApis: string[];
  /** Mapper/repository symbols plus the model classes they declare. */
  persistenceEntities: string[];
}

/* ------------------------------------------------------------------ */
/* Issue 24 / Ticket 04 - Evolution workbench SSE (POST /api/repos/:id/evolve) */
/* ------------------------------------------------------------------ */

/** One pipeline stage of the evolve stream, reported on `repoqa.evolve.stage`. */
export type EvolutionStageId =
  | 'intent_parse'
  | 'target_resolve'
  | 'convention_scan'
  | 'pipeline'
  | 'diagram';

/** Result of the single NLU call (LLM) or its deterministic fallback. */
export interface EvolutionIntentEcho {
  intentType: 'DEPRECATE' | 'EXTEND';
  /** Target phrase extracted from the free-text intent (e.g. "订单"). */
  rawKeyword: string;
  /** Free-text extension goal carried through to the pipeline (EXTEND). */
  extensionGoal?: string;
  /** Symbol the domain radar anchored the keyword to. */
  resolvedTarget?: string;
  /** Radar alternatives the user can switch to (Correction Pill). */
  alternatives: Array<{ symbol: string; score: number }>;
  /** `llm` for the NLU call, `fallback` for the deterministic parser. */
  parsedBy: 'llm' | 'fallback';
}

/** SSE payload of `repoqa.evolve.stage`. */
export interface RepoQaEvolveStage {
  stage: EvolutionStageId;
  /** Stage label for the progress UI. */
  label: string;
  status: 'running' | 'done';
  /** Stage-specific detail (e.g. intent echo after intent_parse resolves). */
  intentEcho?: EvolutionIntentEcho;
}

/** SSE payload of `repoqa.evolve.done` - the four artifact-card sections. */
export interface RepoQaEvolveDone {
  intentEcho: EvolutionIntentEcho;
  /** Engine result: conventions/placement/risks/checklists/blastRadius etc. */
  result: ModuleEvolutionResult;
  /** Engine-rendered physical-edge diagram (ADR-0013) - never model-painted. */
  mermaid?: string;
  /** Physical commit the artifacts were minted against (ADR-0012). */
  commit?: string;
}

/** SSE payload of `repoqa.evolve.error`. */
export interface RepoQaEvolveError {
  error: string;
  /** Structured detail when a STRICT axis or bean cycle blocked the plan. */
  conventionConflict?: ConventionConflictDetail;
}
