export type RepoQATaskType = 'repoqa.index' | 'repoqa.query';

/** v0.6.0 — staged indexing pipeline phases broadcast over SSE/WebSocket. */
export type IndexingPhase =
  | 'DISCOVERY'
  | 'AST_EXTRACTION'
  | 'CROSS_LANG_BRIDGE'
  | 'FINALIZING';

export interface IndexingProgressPayload {
  repoId: string;
  phase: IndexingPhase;
  phaseLabel: string;
  currentFile?: string;
  processedFiles: number;
  totalFiles: number;
  /** 0..100 — 100 only on FINALIZING completion. */
  percent: number;
}

/** v0.6.0 — Architecture Delta symbol/edge summary used by CLI/API/UI. */
export interface ExtractedSymbol {
  name: string;
  file: string;
  lineStart: number;
  lineEnd: number;
  kind: string;
  parentType?: string;
  displayPath?: string;
}

export interface CallEdge {
  from: { file: string; method: string; line: number };
  to: { file: string; method: string; line: number };
}

export interface ArchitectureDeltaReport {
  schemaVersion: number;
  base: string;
  head: string;
  baseSha?: string;
  headSha?: string;
  addedRoutes: ExtractedSymbol[];
  removedRoutes: ExtractedSymbol[];
  brokenEdges: CallEdge[];
  impactedApis: Array<{
    routeSymbol: ExtractedSymbol;
    affectedBySymbols: string[];
    riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  }>;
  /** Reverse/delta Mermaid diagram; optional for small deltas. */
  mermaid?: string;
}

export interface IndexJobInput {
  repoUrl?: string;
  localPath: string;
  branch?: string;
  languages?: string[];
}

export interface IndexJobOutput {
  status: 'cloning' | 'parsing' | 'ready' | 'error';
  repoId: string;
  fileCount: number;
  symbolCount: number;
  error?: string;
}

export interface QueryJobInput {
  repoId: string;
  question: string;
  mode?: 'architecture' | 'call-chain' | 'environment';
}

export interface QueryJobOutput {
  answer: string;
  suggestedAction?: string;
  mermaid?: string;
  anchors?: Array<{
    file: string;
    line: number;
    symbol: string;
  }>;
  trace?: Array<{
    file: string;
    method: string;
    line: number;
  }>;
}

/* ------------------------------------------------------------------ */
/* v0.8.0 — Composite agent tools (deterministic engines)              */
/* ------------------------------------------------------------------ */

/**
 * Chain layers emitted by the diagnose engine. The four canonical layers cover
 * a Java full-stack trace (browser component → HTTP route → service → MyBatis
 * mapper/XML SQL). The model degrades gracefully per language: a TS repo has
 * no DATA_MAPPER layer and simply omits it — layers are never invented, so
 * `DiagnoseLayer` stays open for engine-emitted variants.
 */
export type DiagnoseLayer =
  | 'FRONTEND_COMPONENT'
  | 'HTTP_ROUTER'
  | 'SERVICE'
  | 'DATA_MAPPER'
  | (string & {});

export interface DiagnoseParams {
  repoId: string;
  /** Start symbol: a method name ("handleLike") or "METHOD /route/path". */
  entrySymbol: string;
  /** Free-text symptom, carried through to reports (never used for guessing). */
  symptomDescription?: string;
}

export interface DiagnoseChainStep {
  layer: DiagnoseLayer;
  symbol: string;
  filePath: string;
  line: number;
  status: 'VERIFIED' | 'BROKEN' | 'SUSPECT';
  /** Present on BROKEN steps: the deterministic static-analysis break reason. */
  diagnosticNotes?: string;
  codeSnippet?: string;
}

export interface DiagnoseResult {
  schemaVersion: number;
  repoId: string;
  /** Stable id derived from repo+entry; re-running the same query reuses it. */
  traceId: string;
  entrySymbol: string;
  verifiedChain: DiagnoseChainStep[];
  rootCauseSummary: string;
  /**
   * Empty on the deterministic tool by design (truth-source boundary): patches
   * are generated by the LLM orchestration layer and marked accordingly.
   */
  suggestedPatch?: string;
  suggestedPatchSource?: 'llm-generated';
  cockpitDeepLink: string;
}

export interface RefactorPlanParams {
  repoId: string;
  targetSymbol: string;
  changeType: 'SIGNATURE_CHANGE' | 'REMOVAL' | 'LOGIC_REFACTOR';
}

export interface RefactorPlanResult {
  schemaVersion: number;
  repoId: string;
  targetSymbol: string;
  target: { name: string; file: string; line: number };
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  directCallersCount: number;
  indirectCallersCount: number;
  /** Distinct route paths reachable upstream from the target. */
  impactedRoutes: string[];
  /** Frontend components bridged to the impacted routes (fetch/axios). */
  impactedFrontendComponents: string[];
  migrationSteps: string[];
  cockpitDeepLink: string;
}

/* ------------------------------------------------------------------ */
/* v0.9.0 — Module evolution & domain radar (deterministic engines)    */
/* ------------------------------------------------------------------ */

export interface ModuleEvolutionParams {
  repoId: string;
  /** `DEPRECATE` plans a safe teardown; `EXTEND` plans a decoupled attach. */
  intentType: 'DEPRECATE' | 'EXTEND';
  /** Module name / directory, or a main-flow symbol for EXTEND. */
  targetSymbolOrModule: string;
  /** Free-text extension goal, e.g. "异步敏感词审查"; never used for guessing. */
  extensionGoal?: string;
}

export interface EvolutionChecklistItem {
  category: 'FRONTEND' | 'CONTROLLER' | 'SERVICE' | 'PERSISTENCE' | 'CONFIG';
  action: 'DELETE' | 'MODIFY' | 'CREATE';
  filePath: string;
  description: string;
}

export interface EvolutionScaffoldTemplate {
  suggestedPattern: 'SPRING_EVENT_ASYNC' | 'AOP_ASPECT' | 'DIRECT_INJECTION';
  filePath: string;
  codeSnippet: string;
}

export interface ModuleEvolutionResult {
  schemaVersion: number;
  repoId: string;
  intentType: 'DEPRECATE' | 'EXTEND';
  target: string;
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  blastRadius: {
    impactedCallersCount: number;
    impactedRoutes: string[];
    impactedComponents: string[];
    /** Public symbols that die with the module (fixed-point transitive scan). */
    orphanedSymbols: Array<{ name: string; filePath: string; line: number }>;
  };
  checklists: EvolutionChecklistItem[];
  /**
   * Deterministic scaffolds for EXTEND (recommended shapes, not patches).
   * Empty on DEPRECATE.
   */
  scaffoldTemplates?: EvolutionScaffoldTemplate[];
  /**
   * Empty on the deterministic engine by design (ADR-0006): patches belong to
   * the LLM orchestration layer and are marked llm-generated there.
   */
  suggestedPatch?: string;
  suggestedPatchSource?: 'llm-generated';
  /** Transaction boundary evidence (declaration-level only). */
  transactionBoundaries: Array<{
    symbol: string;
    filePath: string;
    line: number;
    /** METHOD / CLASS / INTERFACE declaration site of the annotation. */
    scope: 'METHOD' | 'CLASS' | 'INTERFACE';
  }>;
  cockpitDeepLink: string;
}

export interface DomainRadarParams {
  repoId: string;
  /** Optional natural-language intent, e.g. "用户点赞". */
  query?: string;
}

export interface DomainRadarAnchor {
  symbol: string;
  type: 'CONTROLLER' | 'SERVICE' | 'ENTITY';
  /** 0..100 deterministic score: fuzzyMatchScore blended with graph rank. */
  relevanceScore: number;
  filePath: string;
  line: number;
  /** v0.11 — incoming call count from the static symbol graph. */
  inDegree: number;
  /** v0.11 — outgoing call count from the static symbol graph. */
  outDegree: number;
}

export interface DomainRadarHub {
  symbol: string;
  inDegree: number;
  outDegree: number;
  /** Deterministic pagerank 0..1 (damping 0.85, sink mass redistributed). */
  pagerank: number;
  role: string;
}

export interface DomainRadarResult {
  schemaVersion: number;
  repoId: string;
  matchedAnchors: DomainRadarAnchor[];
  hubNodes: DomainRadarHub[];
  /** Route entries sorted by graph rank, e.g. "GET /api/owners — listOwners". */
  topApis: string[];
  /** Mapper/repository symbols plus the model classes they declare. */
  persistenceEntities: string[];
}
